#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd

file="/etc/passwd"

# Check if the file exists
if [ -e "$file" ]; then
        # Read the file line by line
        while IFS=: read -r username x uid gid info home shell; do
                echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $info"
        done < "$file"
else
        echo "File does not exist: $file"
fi
