#!/usr/bin/env bash
#Print Best School 10 times, display bad luck, good luck for the 4th and 8th..

x=0
while [ "$x" -lt 10 ]; do
        if [ $x = 3 ]
        then
                echo "bad luck"
	elif [ $x = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
        fi
        x=$((x + 1))
done
