#!/usr/bin/env bash
#Print from 1-10, replace 4th, 9th and 17th..

x=1
while [ "$x" -lt 21 ]; do
	echo $x
	case $x in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
        x=$((x + 1))
done
